services:
  database:
    image: postgres
    container_name: database
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=agata
      - POSTGRES_DB=conta
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: backend
    ports:
      - 3333:3333
    volumes:
      - .:/user/app

volumes:
  pgdata:
    driver: local
